### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement astroid==2.4.0 

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [QAInsights/JEval#3]
While I am installing the required libraries using **_pip install -r requirements.txt_**, I am getting ERROR: No matching distribution found for astroid==2.4.0 (from -r requirements.txt (line 1)).

_Details of the error bellow:_

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement astroid==2.4.0 (from -r requirements.txt (line 1)) (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6)
ERROR: No matching distribution found for astroid==2.4.0 (from -r requirements.txt (line 1))

Is it because of python 2.7 ?

**Comment by JyotiPrakashMallick** [comment]
This is an issue with the backward compatibility, it worked with python 3.6 and higher version.

![sol](https://user-images.githubusercontent.com/6301012/93733517-38fdc000-fbf3-11ea-8a47-524b331cb530.PNG)

**Comment by QAInsights** [comment]
Glad it worked :) @JyotiPrakashMallick
